.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. monkecoin_qt test_monkecoin_qt
clean: FORCE
	$(MAKE) -C .. monkecoin_qt_clean test_monkecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_monkecoin_qt_check
monkecoin-qt monkecoin-qt.exe: FORCE
	$(MAKE) -C .. monkecoin_qt
